### ISSUE TITLE
Permit hypens in link types

### ISSUE THREAD

**Issue by Anusien** [indeedeng/imhotep-builder-jira#10]
Apache Jira supports a link type called "Child-Issue": https://issues.apache.org/jira/rest/api/2/issueLinkType. The imhotep-builder doesn't know how to handle this because it assumes that link text can't contain hypens.

**Comment by Anusien** [comment]
For an example, see the API response for https://issues.apache.org/jira/browse/ARROW-1271.

**Comment by hnarasaki** [comment]
Should this issue be closed?
