### ISSUE TITLE
Add a link to sample Imhotep queries at top of README

### ISSUE THREAD

**Issue by youknowjack** [indeedeng/imhotep-builder-jira#5]
To motivate use of the builder, add a second paragraph in the README that links to (and explains) the apachejira sample queries (http://opensource.indeedeng.io/imhotep/docs/sample-queries/#apachejira).

**Comment by hnarasaki** [comment]
I'd like to take a shot at this one.

**Comment by hnarasaki** [comment]
Created PR: https://github.com/indeedeng/imhotep-builder-jira/pull/40

**Comment by youknowjack** [comment]
Thanks!
